name: Code Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codegen-go:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
        include:
          - os: ubuntu-latest
            go-build: ~/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependency
        run: |
          make install

      - name: Generator Code
        run: |
          make build

      - name: Checkout proto-go repo
        uses: actions/checkout@master
        with:
          repository: go-training/proto-go-demo
          token: ${{ secrets.CI_BOT_TOKEN }}
          path: deploy/proto-go

      - name: Push Code to proto-go-demo
        run: |
          make push-to-go-repo

  codegen-python:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18]
        include:
          - os: ubuntu-latest
            go-build: ~/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependency
        run: |
          make install

      - name: Generator Code
        run: |
          make build

      - name: Checkout proto-go repo
        uses: actions/checkout@master
        with:
          repository: go-training/proto-python-demo
          token: ${{ secrets.CI_BOT_TOKEN }}
          path: deploy/proto-python

      - name: Push Code to proto-python-demo
        run: |
          make push-to-python-repo
